### ISSUE TITLE
Failing to parse/process some vertical files 

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/cnc-masm#4]
```
```
2022/07/29 13:42:12 Configured conversion from charset <nil>
čec 29 13:42:12 kontext-production masm3[3242613]: 2022/07/29 13:42:12 WARNING: using nil structattr accumulator
čec 29 13:42:12 kontext-production masm3[3242613]: 2022/07/29 13:42:12 ...processed 0 lines.
čec 29 13:42:12 kontext-production masm3[3242613]: STOPPING PARSING
čec 29 13:42:12 kontext-production masm3[3242613]: panic: runtime error: index out of range [0] with length 0
čec 29 13:42:12 kontext-production masm3[3242613]: goroutine 6911 [running]:
čec 29 13:42:12 kontext-production masm3[3242613]: github.com/czcorpus/vert-tagextract/v2/db/colgen.intercorp(0xb054c0?, {0xc00239a380?, 0xc0084762f7?, 0x9?})
čec 29 13:42:12 kontext-production masm3[3242613]:         /home/machalek/go/pkg/mod/github.com/czcorpus/vert-tagextract/v2@v2.3.6/db/colgen/functions.go:51 +0x6f
čec 29 13:42:12 kontext-production masm3[3242613]: github.com/czcorpus/vert-tagextract/v2/library.ExtractData.func1.1(0xb05700?)
čec 29 13:42:12 kontext-production masm3[3242613]:         /home/machalek/go/pkg/mod/github.com/czcorpus/vert-tagextract/v2@v2.3.6/library/actions.go:129 +0xe5
čec 29 13:42:12 kontext-production masm3[3242613]: github.com/czcorpus/vert-tagextract/v2/proc.(*TTExtractor).ProcStruct(0xc0003e8780, 0xc013c9c020, 0x1, {0x0, 0x0})
čec 29 13:42:12 kontext-production masm3[3242613]:         /home/machalek/go/pkg/mod/github.com/czcorpus/vert-tagextract/v2@v2.3.6/proc/inserting.go:263 +0x522
čec 29 13:42:12 kontext-production masm3[3242613]: github.com/tomachalek/vertigo/v5.parseVerticalFromScanner(0xc000640300, 0x0, 0xc000435f70, {0xc38dc0, 0xc0003e8780})
čec 29 13:42:12 kontext-production masm3[3242613]:         /home/machalek/go/pkg/mod/github.com/tomachalek/vertigo/v5@v5.1.0/parser.go:363 +0x593
čec 29 13:42:12 kontext-production masm3[3242613]: github.com/tomachalek/vertigo/v5.ParseVerticalFile(0xc000435f70, {0xc38dc0, 0xc0003e8780})
čec 29 13:42:12 kontext-production masm3[3242613]:         /home/machalek/go/pkg/mod/github.com/tomachalek/vertigo/v5@v5.1.0/parser.go:295 +0x2d3
čec 29 13:42:12 kontext-production masm3[3242613]: github.com/czcorpus/vert-tagextract/v2/proc.(*TTExtractor).Run(0xc0003e8780, 0xc000435f70)
čec 29 13:42:12 kontext-production masm3[3242613]:         /home/machalek/go/pkg/mod/github.com/czcorpus/vert-tagextract/v2@v2.3.6/proc/inserting.go:444 +0x185
čec 29 13:42:12 kontext-production masm3[3242613]: github.com/czcorpus/vert-tagextract/v2/library.ExtractData.func1()
čec 29 13:42:12 kontext-production masm3[3242613]:         /home/machalek/go/pkg/mod/github.com/czcorpus/vert-tagextract/v2@v2.3.6/library/actions.go:146 +0x69e
čec 29 13:42:12 kontext-production masm3[3242613]: created by github.com/czcorpus/vert-tagextract/v2/library.ExtractData
čec 29 13:42:12 kontext-production masm3[3242613]:         /home/machalek/go/pkg/mod/github.com/czcorpus/vert-tagextract/v2@v2.3.6/library/actions.go:101 +0x3b0
```

**Comment by tomachalek** [comment]
Unable to reproduce
